/**
 * Created with PyCharm.
 * User: real
 * Date: 12-8-1
 * Time: 下午10:23
 * To change this template use File | Settings | File Templates.
 */
offsets = ['+12', '+11', '+10', '+9', '+8', '+7', '+6', '+5', '+4', '+3', '+2', '+1',
    '0', '-1', '-2', '-3', '-4', '-5', '-6', '-7', '-8', '-9', '-10', '-11', '-12'];

timezones = {
    '+12' : ['Asia/Anadyr', 'Asia/Kamchatka', 'Asia/Magadan', 'Etc/GMT+12', 'Etc/GMT-12', 'Kwajalein', 'Pacific/Funafuti', 'Pacific/Kwajalein', 'Pacific/Majuro', 'Pacific/Nauru', 'Pacific/Tarawa', 'Pacific/Wake', 'Pacific/Wallis'],
    '+11' : ['Antarctica/Casey', 'Antarctica/Macquarie', 'Asia/Sakhalin', 'Asia/Vladivostok', 'Australia/ACT', 'Australia/Canberra', 'Australia/Currie', 'Australia/Hobart', 'Australia/LHI', 'Australia/Lord_Howe', 'Australia/Melbourne', 'Australia/NSW', 'Australia/Sydney', 'Australia/Tasmania', 'Australia/Victoria', 'Etc/GMT-11', 'Pacific/Efate', 'Pacific/Guadalcanal', 'Pacific/Kosrae', 'Pacific/Noumea', 'Pacific/Pohnpei', 'Pacific/Ponape'],
    '+10' : ['Antarctica/DumontDUrville', 'Asia/Yakutsk', 'Australia/Brisbane', 'Australia/Lindeman', 'Australia/Queensland', 'Etc/GMT-10', 'Pacific/Chuuk', 'Pacific/Guam', 'Pacific/Port_Moresby', 'Pacific/Saipan', 'Pacific/Truk', 'Pacific/Yap'],
    '+9': ['Asia/Dili', 'Asia/Irkutsk', 'Asia/Jayapura', 'Asia/Pyongyang', 'Asia/Seoul', 'Asia/Tokyo', 'Etc/GMT-9', 'Japan', 'Pacific/Palau', 'ROK'],
    '+8': ['Asia/Brunei', 'Asia/Choibalsan', 'Asia/Chongqing', 'Asia/Chungking', 'Asia/Harbin', 'Asia/Hong_Kong', 'Asia/Kashgar', 'Asia/Krasnoyarsk', 'Asia/Kuala_Lumpur', 'Asia/Kuching', 'Asia/Macao', 'Asia/Macau', 'Asia/Makassar', 'Asia/Manila', 'Asia/Shanghai', 'Asia/Singapore', 'Asia/Taipei', 'Asia/Ujung_Pandang', 'Asia/Ulaanbaatar', 'Asia/Ulan_Bator', 'Asia/Urumqi', 'Australia/Perth', 'Australia/West', 'Etc/GMT-8', 'Hongkong', 'PRC', 'ROC', 'Singapore'],
    '+7': ['Asia/Bangkok', 'Asia/Ho_Chi_Minh', 'Asia/Hovd', 'Asia/Jakarta', 'Asia/Novokuznetsk', 'Asia/Novosibirsk', 'Asia/Omsk', 'Asia/Phnom_Penh', 'Asia/Pontianak', 'Asia/Saigon', 'Asia/Vientiane', 'Etc/GMT-7', 'Indian/Christmas'],
    '+6': ['Antarctica/Vostok', 'Asia/Almaty', 'Asia/Bishkek', 'Asia/Dacca', 'Asia/Dhaka', 'Asia/Qyzylorda', 'Asia/Thimbu', 'Asia/Thimphu', 'Asia/Yekaterinburg', 'Etc/GMT-6', 'Indian/Chagos'],
    '+5': ['Antarctica/Davis', 'Antarctica/Mawson', 'Asia/Aqtau', 'Asia/Aqtobe', 'Asia/Ashgabat', 'Asia/Ashkhabad', 'Asia/Dushanbe', 'Asia/Karachi', 'Asia/Oral', 'Asia/Samarkand', 'Asia/Tashkent', 'Etc/GMT-5', 'Indian/Kerguelen', 'Indian/Maldives'],
    '+4': ['Asia/Baku', 'Asia/Dubai', 'Asia/Muscat', 'Asia/Tbilisi', 'Asia/Yerevan', 'Etc/GMT-4', 'Europe/Moscow', 'Europe/Samara', 'Europe/Volgograd', 'Indian/Mahe', 'Indian/Mauritius', 'Indian/Reunion', 'W-SU'],
    '+3': ['Africa/Addis_Ababa', 'Africa/Asmara', 'Africa/Asmera', 'Africa/Dar_es_Salaam', 'Africa/Djibouti', 'Africa/Juba', 'Africa/Kampala', 'Africa/Khartoum', 'Africa/Mogadishu', 'Africa/Nairobi', 'Antarctica/Syowa', 'Asia/Aden', 'Asia/Baghdad', 'Asia/Bahrain', 'Asia/Kuwait', 'Asia/Qatar', 'Asia/Riyadh', 'Etc/GMT-3', 'Europe/Kaliningrad', 'Europe/Minsk', 'Indian/Antananarivo', 'Indian/Comoro', 'Indian/Mayotte'],
    '+2': ['Africa/Blantyre', 'Africa/Bujumbura', 'Africa/Cairo', 'Africa/Gaborone', 'Africa/Harare', 'Africa/Johannesburg', 'Africa/Kigali', 'Africa/Lubumbashi', 'Africa/Lusaka', 'Africa/Maputo', 'Africa/Maseru', 'Africa/Mbabane', 'Africa/Tripoli', 'Africa/Windhoek', 'Asia/Amman', 'Asia/Beirut', 'Asia/Damascus', 'Asia/Gaza', 'Asia/Hebron', 'Asia/Istanbul', 'Asia/Jerusalem', 'Asia/Nicosia', 'Asia/Tel_Aviv', 'EET', 'Egypt', 'Etc/GMT-2', 'Europe/Athens', 'Europe/Bucharest', 'Europe/Chisinau', 'Europe/Helsinki', 'Europe/Istanbul', 'Europe/Kiev', 'Europe/Mariehamn', 'Europe/Nicosia', 'Europe/Riga', 'Europe/Simferopol', 'Europe/Sofia', 'Europe/Tallinn', 'Europe/Tiraspol', 'Europe/Uzhgorod', 'Europe/Vilnius', 'Europe/Zaporozhye', 'Israel', 'Libya', 'Turkey'],
    '+1': ['Africa/Algiers', 'Africa/Bangui', 'Africa/Brazzaville', 'Africa/Ceuta', 'Africa/Douala', 'Africa/Kinshasa', 'Africa/Lagos', 'Africa/Libreville', 'Africa/Luanda', 'Africa/Malabo', 'Africa/Ndjamena', 'Africa/Niamey', 'Africa/Porto-Novo', 'Africa/Tunis', 'Arctic/Longyearbyen', 'Atlantic/Jan_Mayen', 'CET', 'Etc/GMT-1', 'Europe/Amsterdam', 'Europe/Andorra', 'Europe/Belgrade', 'Europe/Berlin', 'Europe/Bratislava', 'Europe/Brussels', 'Europe/Budapest', 'Europe/Copenhagen', 'Europe/Gibraltar', 'Europe/Ljubljana', 'Europe/Luxembourg', 'Europe/Madrid', 'Europe/Malta', 'Europe/Monaco', 'Europe/Oslo', 'Europe/Paris', 'Europe/Podgorica', 'Europe/Prague', 'Europe/Rome', 'Europe/San_Marino', 'Europe/Sarajevo', 'Europe/Skopje', 'Europe/Stockholm', 'Europe/Tirane', 'Europe/Vaduz', 'Europe/Vatican', 'Europe/Vienna', 'Europe/Warsaw', 'Europe/Zagreb', 'Europe/Zurich', 'MET', 'Poland'],
    '0': ['Africa/Abidjan', 'Africa/Accra', 'Africa/Bamako', 'Africa/Banjul', 'Africa/Bissau', 'Africa/Casablanca', 'Africa/Conakry', 'Africa/Dakar', 'Africa/El_Aaiun', 'Africa/Freetown', 'Africa/Lome', 'Africa/Monrovia', 'Africa/Nouakchott', 'Africa/Ouagadougou', 'Africa/Sao_Tome', 'Africa/Timbuktu', 'America/Danmarkshavn', 'Atlantic/Canary', 'Atlantic/Faeroe', 'Atlantic/Faroe', 'Atlantic/Madeira', 'Atlantic/Reykjavik', 'Atlantic/St_Helena', 'Eire', 'Etc/GMT', 'Etc/GMT+0', 'Etc/GMT-0', 'Etc/GMT0', 'Etc/Greenwich', 'Etc/UCT', 'Etc/UTC', 'Etc/Universal', 'Etc/Zulu', 'Europe/Belfast', 'Europe/Dublin', 'Europe/Guernsey', 'Europe/Isle_of_Man', 'Europe/Jersey', 'Europe/Lisbon', 'Europe/London', 'GB', 'GB-Eire', 'GMT', 'GMT+0', 'GMT-0', 'GMT0', 'Greenwich', 'Iceland', 'Portugal', 'UCT', 'UTC', 'Universal', 'WET', 'Zulu'],
    '-1' : ['Antarctica/McMurdo', 'Antarctica/South_Pole', 'Etc/GMT+11', 'Etc/GMT-13', 'NZ', 'Pacific/Auckland', 'Pacific/Enderbury', 'Pacific/Fiji', 'Pacific/Midway', 'Pacific/Niue', 'Pacific/Pago_Pago', 'Pacific/Samoa', 'Pacific/Tongatapu', 'US/Samoa'],
    '-2' : ['America/Adak', 'America/Atka', 'Etc/GMT+10', 'Etc/GMT-14', 'HST', 'Pacific/Apia', 'Pacific/Fakaofo', 'Pacific/Honolulu', 'Pacific/Johnston', 'Pacific/Kiritimati', 'Pacific/Rarotonga', 'Pacific/Tahiti', 'US/Aleutian', 'US/Hawaii'],
    '-3': ['America/Anchorage', 'America/Juneau', 'America/Nome', 'America/Sitka', 'America/Yakutat', 'Etc/GMT+9', 'Pacific/Gambier', 'US/Alaska'],
    '-4': ['America/Dawson', 'America/Ensenada', 'America/Los_Angeles', 'America/Metlakatla', 'America/Santa_Isabel', 'America/Tijuana', 'America/Vancouver', 'America/Whitehorse', 'Canada/Pacific', 'Canada/Yukon', 'Etc/GMT+8', 'Mexico/BajaNorte', 'PST8PDT', 'Pacific/Pitcairn', 'US/Pacific', 'US/Pacific-New'],
    '-5': ['America/Boise', 'America/Cambridge_Bay', 'America/Chihuahua', 'America/Creston', 'America/Dawson_Creek', 'America/Denver', 'America/Edmonton', 'America/Hermosillo', 'America/Inuvik', 'America/Mazatlan', 'America/Ojinaga', 'America/Phoenix', 'America/Shiprock', 'America/Yellowknife', 'Canada/Mountain', 'Etc/GMT+7', 'MST', 'MST7MDT', 'Mexico/BajaSur', 'Navajo', 'US/Arizona', 'US/Mountain'],
    '-6': ['America/Bahia_Banderas', 'America/Belize', 'America/Cancun', 'America/Chicago', 'America/Costa_Rica', 'America/El_Salvador', 'America/Guatemala', 'America/Indiana/Knox', 'America/Indiana/Tell_City', 'America/Knox_IN', 'America/Managua', 'America/Matamoros', 'America/Menominee', 'America/Merida', 'America/Mexico_City', 'America/Monterrey', 'America/North_Dakota/Beulah', 'America/North_Dakota/Center', 'America/North_Dakota/New_Salem', 'America/Rainy_River', 'America/Rankin_Inlet', 'America/Regina', 'America/Resolute', 'America/Swift_Current', 'America/Tegucigalpa', 'America/Winnipeg', 'CST6CDT', 'Canada/Central', 'Canada/East-Saskatchewan', 'Canada/Saskatchewan', 'Etc/GMT+6', 'Mexico/General', 'Pacific/Galapagos', 'US/Central', 'US/Indiana-Starke'],
    '-7': ['America/Atikokan', 'America/Bogota', 'America/Cayman', 'America/Coral_Harbour', 'America/Detroit', 'America/Fort_Wayne', 'America/Grand_Turk', 'America/Guayaquil', 'America/Havana', 'America/Indiana/Indianapolis', 'America/Indiana/Marengo', 'America/Indiana/Petersburg', 'America/Indiana/Vevay', 'America/Indiana/Vincennes', 'America/Indiana/Winamac', 'America/Indianapolis', 'America/Iqaluit', 'America/Jamaica', 'America/Kentucky/Louisville', 'America/Kentucky/Monticello', 'America/Lima', 'America/Louisville', 'America/Montreal', 'America/Nassau', 'America/New_York', 'America/Nipigon', 'America/Panama', 'America/Pangnirtung', 'America/Port-au-Prince', 'America/Thunder_Bay', 'America/Toronto', 'Canada/Eastern', 'Chile/EasterIsland', 'Cuba', 'EST', 'EST5EDT', 'Etc/GMT+5', 'Jamaica', 'Pacific/Easter', 'US/East-Indiana', 'US/Eastern', 'US/Michigan'],
    '-8': ['America/Anguilla', 'America/Antigua', 'America/Aruba', 'America/Barbados', 'America/Blanc-Sablon', 'America/Boa_Vista', 'America/Curacao', 'America/Dominica', 'America/Eirunepe', 'America/Glace_Bay', 'America/Goose_Bay', 'America/Grenada', 'America/Guadeloupe', 'America/Guyana', 'America/Halifax', 'America/Kralendijk', 'America/La_Paz', 'America/Lower_Princes', 'America/Manaus', 'America/Marigot', 'America/Martinique', 'America/Moncton', 'America/Montserrat', 'America/Port_of_Spain', 'America/Porto_Acre', 'America/Porto_Velho', 'America/Puerto_Rico', 'America/Rio_Branco', 'America/Santo_Domingo', 'America/St_Barthelemy', 'America/St_Kitts', 'America/St_Lucia', 'America/St_Thomas', 'America/St_Vincent', 'America/Thule', 'America/Tortola', 'America/Virgin', 'Atlantic/Bermuda', 'Brazil/Acre', 'Brazil/West', 'Canada/Atlantic', 'Etc/GMT+4'],
    '-9': ['America/Araguaina', 'America/Argentina/Buenos_Aires', 'America/Argentina/Catamarca', 'America/Argentina/ComodRivadavia', 'America/Argentina/Cordoba', 'America/Argentina/Jujuy', 'America/Argentina/La_Rioja', 'America/Argentina/Mendoza', 'America/Argentina/Rio_Gallegos', 'America/Argentina/Salta', 'America/Argentina/San_Juan', 'America/Argentina/San_Luis', 'America/Argentina/Tucuman', 'America/Argentina/Ushuaia', 'America/Asuncion', 'America/Belem', 'America/Buenos_Aires', 'America/Campo_Grande', 'America/Catamarca', 'America/Cayenne', 'America/Cordoba', 'America/Cuiaba', 'America/Fortaleza', 'America/Godthab', 'America/Jujuy', 'America/Maceio', 'America/Mendoza', 'America/Miquelon', 'America/Paramaribo', 'America/Recife', 'America/Rosario', 'America/Santarem', 'America/Santiago', 'Antarctica/Palmer', 'Antarctica/Rothera', 'Atlantic/Stanley', 'Chile/Continental', 'Etc/GMT+3'],
    '-10': ['America/Bahia', 'America/Montevideo', 'America/Noronha', 'America/Sao_Paulo', 'Atlantic/South_Georgia', 'Brazil/DeNoronha', 'Brazil/East', 'Etc/GMT+2'],
    '-11': ['America/Scoresbysund', 'Atlantic/Azores', 'Atlantic/Cape_Verde', 'Etc/GMT+1']
};